#!/usr/bin/env bash
# Boot jos under QEMU, wait for the user program to exit, then snapshot memory
# via the QEMU monitor (HMP over a Unix socket) into dumps/ for offline
# exploration with a hex viewer (xxd, ImHex, Hex Fiend, ...).
set -euo pipefail

cd "$(dirname "$0")"
cargo build -q
KERNEL=target/aarch64-unknown-none/debug/jos
USER_ELF=target/aarch64-unknown-none/debug/user

RAM_BASE=0x40000000
RAM_SIZE=$((128 * 1024 * 1024))
USER_STACK_VA=0x200100000
PAGE=4096

DUMPS=dumps
rm -rf "$DUMPS"
mkdir -p "$DUMPS"

TMP="$(mktemp -d)"
SERIAL="$TMP/serial.txt"
MON="$TMP/monitor.sock"
trap 'kill "$QPID" 2>/dev/null || true; rm -rf "$TMP"' EXIT

qemu-system-aarch64 -machine virt,gic-version=3 -cpu cortex-a72 -nographic \
    -monitor "unix:$MON,server,nowait" \
    -kernel "$KERNEL" >"$SERIAL" 2>&1 &
QPID=$!

# Wait for the interesting moment: the user program has run and exited, the
# kernel is parked in wfi with the MMU on and the user mappings still live.
echo "booting jos..."
for _ in $(seq 1 75); do
    grep -qF "[user] exited with code 0" "$SERIAL" && break
    sleep 0.2
done
if ! grep -qF "[user] exited with code 0" "$SERIAL"; then
    echo "FAIL: user program never exited. Serial output:" >&2
    cat "$SERIAL" >&2
    exit 1
fi
echo "user exited - dumping"

# Send one HMP command; the trailing sleep keeps the socket open long enough
# for the monitor to receive it (execution is server-side and synchronous).
# NOTE: filename arguments must be double-quoted in the command string —
# otherwise HMP's expression parser reads `4096 /tmp/x` as a division.
mon() {
    { printf '%s\n' "$1"; sleep 0.3; } | nc -U "$MON" >/dev/null
}

# Wait until a dump file exists with exactly the expected size.
expect_file() {
    local f=$1 size=$2
    for _ in $(seq 1 50); do
        [ -f "$f" ] && [ "$(stat -f%z "$f")" -eq "$size" ] && return 0
        sleep 0.2
    done
    echo "FAIL: $f missing or not $size bytes." >&2
    exit 1
}

# Round $1 up to the next page boundary.
page_align() { echo $(( ($1 + PAGE - 1) & ~(PAGE - 1) )); }

ABS_DUMPS="$(pwd)/$DUMPS"
MAP="$DUMPS/MAP.txt"
{
    echo "jos memory snapshot, taken after '[user] exited with code 0'"
    echo "generated by dump.sh on $(date)"
    echo
    echo "file offset -> address: for ram.bin, PA = $RAM_BASE + offset."
    echo "memsave files are virtual-address ranges read through the live EL1 page tables."
    echo
} >"$MAP"

# Full physical RAM: kernel image (at PA 0x40080000 = offset 0x80000), page
# tables, heap frames, scheduler stacks, loaded user frames.
mon "pmemsave $RAM_BASE $RAM_SIZE \"$ABS_DUMPS/ram.bin\""
expect_file "$DUMPS/ram.bin" "$RAM_SIZE"
echo "  $DUMPS/ram.bin  (128 MiB physical RAM @ $RAM_BASE)"
echo "ram.bin         $RAM_SIZE bytes, physical $RAM_BASE (kernel image at offset 0x80000)" >>"$MAP"

# Each PT_LOAD segment of the user program, by virtual address. Parsed from the
# ELF so the dumps track the program as it grows segments.
i=0
objdump -p "$USER_ELF" | awk '
    /LOAD/      { vaddr = $5 }
    /filesz/    { print vaddr, $4, $6 }
' | while read -r vaddr memsz flags; do
    size=$(page_align $((memsz)))
    out="user-seg$i-$(echo "$flags" | tr -d -- '-').bin"
    mon "memsave $vaddr $size \"$ABS_DUMPS/$out\""
    expect_file "$DUMPS/$out" "$size"
    echo "  $DUMPS/$out  (user segment @ $vaddr, $flags)"
    echo "$out  $size bytes, virtual $vaddr ($flags PT_LOAD segment)" >>"$MAP"
    i=$((i + 1))
done

# The user stack page (mapped by the kernel, not an ELF segment).
mon "memsave $USER_STACK_VA $PAGE \"$ABS_DUMPS/user-stack.bin\""
expect_file "$DUMPS/user-stack.bin" "$PAGE"
echo "  $DUMPS/user-stack.bin  (user stack @ $USER_STACK_VA)"
echo "user-stack.bin  $PAGE bytes, virtual $USER_STACK_VA (user stack page)" >>"$MAP"

mon "quit"
wait "$QPID" 2>/dev/null || true

cp "$SERIAL" "$DUMPS/serial.txt"
{
    echo "serial.txt      the boot transcript that accompanied this snapshot"
    echo
    echo "key addresses:"
    echo "  0x40080000   kernel image base (linker.ld)"
    echo "  0x100000000  kernel heap virtual window (allocator.rs)"
    echo "  0x200000000  user program link base (user/user.ld)"
    echo "  $USER_STACK_VA  user stack (kernel/src/user.rs)"
    echo
    echo "symbol addresses: nm $KERNEL | sort   (or nm $USER_ELF)"
} >>"$MAP"

echo "done. see $DUMPS/MAP.txt for the legend."
