//! The embedded userspace programs.
//!
//! `kernel/build.rs` discovers every binary in `user/src/bin/` and generates the
//! `PROGRAMS` table — `(name, ELF bytes)` — included below. This is the registry
//! a future `OP_SPAWN` will resolve a program name against; for now `kmain` looks
//! programs up by name to decide what to boot.

// Generated by build.rs: `pub static PROGRAMS: &[(&str, &[u8])] = &[ ... ];`
include!(concat!(env!("OUT_DIR"), "/programs.rs"));

/// The ELF image of the program named `name`, if embedded.
pub fn get(name: &str) -> Option<&'static [u8]> {
    PROGRAMS
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, bytes)| *bytes)
}
